version: '3'

services:

  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - '6379'

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: drf
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER} -d drf" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build: .
    tty: true
    ports:
      - '8000:8000'
    command: sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info --pool=prefork --concurrency=4
    environment:
      DATABASE_URL: postgres://${USER}:${PASSWORD}@db:5432/drf
      REDIS_URL: ${REDIS_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_BROKER_URL}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - backend

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      DATABASE_URL: postgres://${USER}:${PASSWORD}@db:5432/drf
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery:
        condition: service_started
    env_file:
      - ./.env
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: